site_name: Game Combat 2D
site_url: https://brayaan.github.io/game-combat-2d/
repo_url: https://github.com/Brayaan/game-combat-2d
repo_name: Brayaan/game-combat-2d

theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  palette:
    - scheme: slate
      primary: custom
      accent: custom
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - attr_list
  - md_in_html

nav:
  - Inicio: index.md
  - Overview: 00-overview.md
  - User Manual: 08-manual-usuario.md
  - Controls: 01-controls.md
  - Combat System: 02-combat-system.md
  - Health System: 03-health-system.md
  - Energy System: 04-energy-system.md
  - UI System: 06-ui-system.md
  - Game Rules: 05-game-rules.md
  - Game Behavior: 07-game-behavior.md

extra_css:
  - stylesheets/extra.css?v=2

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Brayaan
      name: GitHub del Creador
  generator: false

copyright: Copyright &copy; 2026 Brayaan - Game Combat 2D